FROM docker.elastic.co/elasticsearch/elasticsearch:7.17.0

RUN apt-get update

#RUN apt-get -y install python
#RUN curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output /get-pip.py
#RUN python /get-pip.py
#RUN mkdir /scripts
#COPY ./scripts/elasticPopulate.py /scripts/
#COPY ./scripts/requirements.txt /scripts/
#COPY ./scripts/dummy.json /scripts/
#COPY ./scripts/exec.sh /scripts/
#RUN pip install -r /scripts/requirements.txt

EXPOSE 9200

EXPOSE 9300