version: "3"
services:
  crud-php:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html/
    networks:
      - crud-network
  mysql-app:
    build: 
      context: .
      dockerfile: mysql.Dockerfile
    ports:
      - "3306:3306"
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./docker/data-mysql:/var/lib/mysql
      #- ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: crud_php
      MYSQL_ROOT_PASSWORD: JGnf43!@
    networks:
      - crud-network

networks:
  crud-network:
    driver: bridge
