version: "3"
services:
  crud-php:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html/
    networks:
      - crud-network
  mysql-app:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./docker/dbdata:/var/lib/mysql
      - ./docker/dbbkp:/root/
    environment:
      MYSQL_DATABASE: crud_php
      MYSQL_ROOT_PASSWORD: JGnf43!@
    networks:
      - crud-network
    #command: bash -c "apt-get update -y && apt-get install iputils-ping -y"
    #command: bash -c "/var/lib/mysql/verifyTable.sh people"

networks:
  crud-network:
    driver: bridge
